name: abimongo_utils

on:
  push:
    branches:
      - main
      - 'release/**'
    tags:
      - 'v*.*.*'
      
  pull_request:
    branches: 
      - main, 
      - 'releases/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'


      - name: Install dependencies
        run: npm ci
 
      # - name: Lint
      #   run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: abimongo_core-build-${{ github.run_number }}-${{ github.sha }}
          path: |
            ./dist
            ./package.json
            ./README.md
            ./LICENSE
          if-no-files-found: error
          retention-days: 14

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/head/main')
        run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
